// const calcButtons =[
//     {
//         id:1,
//         icon:"%",
//         styleClass:styles.funButton,
        
//     },
//     {
//         id:2,
//         icon:"CE",
//         styleClass:styles.funButton,
//     },
//     {
//         id:3,
//         icon:"C",
//         styleClass:styles.funButton,
//     },
//     {
//         id:4,
//         icon:<BackspaceIcon />,
//         styleClass:styles.backSpace,
//     },
//     {
//         id:5,
//         icon:"1/x",
//         styleClass:styles.funButton,
//     },
//     {
//         id:6,
//         icon:<span>&#8730;</span>,
//         styleClass:styles.funButton,
//     },
//     {
//         id:7,
//         icon:<span>&divide;</span>,
//         styleClass:styles.funButton,
//     },
//     {
//         id:8,
//         icon:<span>&#247;</span>,
//         styleClass:styles.funButton,
//     },
//     {
//         id:9,
//         icon:1,
//         styleClass:styles.numberButton,
//         val:1,
//     },
//     {
//         id:10,
//         icon:2,
//         styleClass:styles.numberButton,
//         val:2,
//     },
//     {
//         id:11,
//         icon:3,
//         styleClass:styles.numberButton,
//         val:3,
//     },
//     {
//         id:12,
//         icon:<span>&#215;</span>,
//         styleClass:styles.funButton,
//     },
//     {
//         id:13,
//         icon:4,
//         styleClass:styles.numberButton,
//         val:4,
//     },
//     {
//         id:14,
//         icon:5,
//         styleClass:styles.numberButton,
//         val:5,
//     },
//     {
//         id:15,
//         icon:6,
//         styleClass:styles.numberButton,
//         val:6,
//     },
//     {
//         id:16,
//         icon:<span>&#8722;</span>,
//         styleClass:styles.funButton,
//     },
//     {
//         id:17,
//         icon:7,
//         styleClass:styles.numberButton,
//         val:7,
//     },
//     {
//         id:18,
//         icon:8,
//         styleClass:styles.numberButton,
//         val:8,
//     },
//     {
//         id:19,
//         icon:9,
//         styleClass:styles.numberButton,
//         val:9,
//     },
//     {
//         id:20,
//         icon:<span>&#43;</span>,
//         styleClass:styles.funButton,
//         clickFunction:add,
        
//     },
//     {
//         id:21,
//         icon:"+/-",
//         styleClass:styles.funButton,
//     },
//     {
//         id:22,
//         icon:0,
//         styleClass:styles.numberButton,
//         val:0,
//     },
//     {
//         id:23,
//         icon:"." ,
//         styleClass:styles.funButton,
//     },
//     {
//         id:24,
//         icon:"=",
//         styleClass:styles.equalButton,
//     },
// ]


// export { calcButtons} ;

// {calcButtons.map((el,index)=>{
//     return(
//       <>
//        <Grid item xs={3} key ={el.id}  >
//            <Paper style={styles.btnGrid} >
//            <Button variant="contained" value ={el.val} onClick ={(el)=>el.clickFunction(el)} style={el.styleClass}>{el.icon}</Button> 
//              </Paper>
//       </Grid>
//     </>
//     )
    
//   })}